services:
  postgres:
    image: postgres:16-alpine
    container_name: swiftroute-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: swiftroute_db
      POSTGRES_USER: swiftroute
      POSTGRES_PASSWORD: swiftroute_secret
    ports:
      - "5432:5432"
    volumes:
      - swiftroute_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swiftroute -d swiftroute_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: swiftroute-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - swiftroute_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  swiftroute_pgdata:
  swiftroute_redisdata:
